- docs/site/getting-started/getting-started-host-app.md
- docs/site/getting-started/getting-started-shopping-cart-app.md
- docs/site/getting-started/getting-started.md
> Simplify the reading of some phrases in the Getting Started Guide

- CHANGELOG.md
- docs/site/changelog/changelog.md
- package-lock.json
- package.json
- projects/scion/microfrontend-platform/package.json
> release: v1.0.0-beta.2

- CHANGELOG.md
- docs/site/changelog/changelog.md
- package-lock.json
- package.json
- projects/scion/microfrontend-platform/package.json
> release: v1.0.0-beta.3

- CHANGELOG.md
- docs/site/changelog/changelog.md
- package-lock.json
- package.json
- projects/scion/microfrontend-platform/package.json
> release: v1.0.0-beta.4

- CHANGELOG.md
- docs/site/changelog/changelog.md
- package-lock.json
- package.json
- projects/scion/microfrontend-platform/package.json
> release: v1.0.0-beta.5

- docs/adoc/microfrontend-platform-developer-guide/chapters/core-concepts/intention-api/intention-api.snippets.ts
- docs/adoc/microfrontend-platform-developer-guide/chapters/core-concepts/overview/overview.adoc
- docs/adoc/microfrontend-platform-developer-guide/chapters/terminology/terminology.adoc
> docs(platform): fix broken links and improve code example

- docs/site/getting-started/getting-started-host-app.md
- docs/site/getting-started/getting-started-shopping-cart-app.md
- docs/site/installation.md
- tslint.json
> docs(platform): fix wrong application config type

- docs/adoc/microfrontend-platform-developer-guide/chapters/core-concepts/overview/overview.adoc
- docs/adoc/microfrontend-platform-developer-guide/chapters/miscellaneous/angular-integration-guide/angular-integration-guide.adoc
> docs: fix typos in developer guide

- CHANGELOG.md
- docs/site/changelog/changelog.md
- package-lock.json
- package.json
- projects/scion/microfrontend-platform/package.json
> release: v1.0.0-beta.8

- CHANGELOG.md
- docs/site/changelog/changelog.md
- package-lock.json
- package.json
- projects/scion/microfrontend-platform/package.json
> release: v1.0.0-beta.9

- CHANGELOG.md
- docs/site/changelog/changelog.md
- package-lock.json
- package.json
- projects/scion/microfrontend-platform/package.json
> release: v1.0.0-beta.10

- CHANGELOG.md
- docs/site/changelog/changelog.md
- package-lock.json
- package.json
- projects/scion/microfrontend-platform/package.json
> release: v1.0.0-beta.12

- CHANGELOG.md
- docs/site/changelog/changelog.md
- package-lock.json
- package.json
- projects/scion/microfrontend-platform/package.json
> release: v1.0.0-beta.13

- CHANGELOG.md
- docs/site/changelog/changelog.md
> docs(platform): add note about breaking change to the changelog

- CHANGELOG.md
- docs/site/changelog/changelog.md
- package-lock.json
- package.json
- projects/scion/microfrontend-platform/package.json
> release: v1.0.0-beta.14

- CHANGELOG.md
- docs/site/changelog/changelog.md
- package-lock.json
- package.json
- projects/scion/microfrontend-platform/package.json
> release: v1.0.0-beta.16

- CHANGELOG.md
- docs/site/changelog/changelog.md
- package-lock.json
- package.json
- projects/scion/microfrontend-platform/package.json
> release: v1.0.0-beta.17

- .eslintrc.json
- package-lock.json
- package.json
- projects/scion/microfrontend-platform/src/lib/host/manifest-registry/ɵmanifest-registry.ts
> chore: add eslint deprecation plugin

- CHANGELOG.md
- docs/site/changelog/changelog.md
- package-lock.json
- package.json
- projects/scion/microfrontend-platform/package.json
> release: v1.0.0-beta.18

- projects/scion/microfrontend-platform.e2e/src/messaging/intent-based-messaging-specs.ts
- projects/scion/microfrontend-platform.e2e/src/messaging/messaging.e2e-spec.ts
- projects/scion/microfrontend-platform/src/lib/host/manifest-registry/manifest-registry.spec.ts
- projects/scion/microfrontend-platform/src/lib/host/manifest-registry/ɵmanifest-registry.ts
> fix(platform): prevent dispatching implicit intents to public capabilities of other applications

- CHANGELOG.md
- docs/site/changelog/changelog.md
- package-lock.json
- package.json
- projects/scion/microfrontend-platform/package.json
> release: v1.0.0-beta.19

- .npmrc
- package-lock.json
> chore: use tls for connecting to npm registry

- CHANGELOG.md
- docs/site/changelog/changelog.md
- package-lock.json
- package.json
- projects/scion/microfrontend-platform/package.json
- projects/scion/microfrontend-platform/src/lib/microfrontend-platform.ts
> release: v1.0.0-rc.2

- projects/scion/microfrontend-platform/package.json
- projects/scion/microfrontend-platform/src/lib/client/manifest-registry/manifest-service.ts
- projects/scion/microfrontend-platform/src/lib/client/messaging/broker-gateway.ts
- projects/scion/microfrontend-platform/src/lib/client/messaging/messaging.spec.ts
- projects/scion/microfrontend-platform/src/lib/host/message-broker/message-broker.ts
- projects/scion/microfrontend-platform/src/lib/microfrontend-platform.ts
- projects/scion/microfrontend-platform/src/lib/platform-property-service.ts
> refactor(platform): register beans to be initialized in a specific runlevel as initializers

- apps/microfrontend-platform-testing-app/src/app/app.module.ts
- apps/microfrontend-platform-testing-app/src/app/messaging/append-param-data-type.pipe.ts
- apps/microfrontend-platform-testing-app/src/app/messaging/message-list-item/message-list-item.component.html
- apps/microfrontend-platform-testing-app/src/app/messaging/message-list-item/message-list-item.component.ts
- apps/microfrontend-platform-testing-app/src/app/messaging/publish-message/publish-message.component.ts
- projects/scion/microfrontend-platform.e2e/src/messaging/intent-based-messaging-specs.ts
- projects/scion/microfrontend-platform.e2e/src/messaging/messaging.e2e-spec.ts
- projects/scion/microfrontend-platform/src/lib/client/messaging/messaging.spec.ts
- projects/scion/microfrontend-platform/src/lib/host/message-broker/message-broker.ts
- projects/scion/microfrontend-platform/src/lib/host/message-broker/param-matcher.spec.ts
- projects/scion/microfrontend-platform/src/lib/host/message-broker/param-matcher.ts
- projects/scion/microfrontend-platform/src/lib/testing/spec.util.spec.ts
> fix(platform): discard intent parameter if set to `undefined`

- apps/microfrontend-platform-testing-app/src/app/platform-initializer.service.ts
- docs/adoc/microfrontend-platform-developer-guide/chapters/core-concepts/cross-application-communication/message-interception.snippets.ts
- projects/scion/microfrontend-platform.e2e/src/messaging/messaging.e2e-spec.ts
- projects/scion/microfrontend-platform.e2e/src/messaging/topic-based-messaging-specs.ts
- projects/scion/microfrontend-platform/src/lib/client/messaging/messaging.spec.ts
- projects/scion/microfrontend-platform/src/lib/host/message-broker/message-broker.ts
- projects/scion/microfrontend-platform/src/lib/host/message-broker/message-interception.spec.ts
- projects/scion/microfrontend-platform/src/lib/host/message-broker/message-interception.ts
- projects/scion/microfrontend-platform/src/lib/host/router/microfrontend-intent.interceptor.ts
> fix(platform): report message rejection of asynchronous interceptors back to the sender

- projects/scion/microfrontend-platform.e2e/src/messaging/intent-based-messaging-specs.ts
- projects/scion/microfrontend-platform.e2e/src/router-outlet/router-outlet.e2e-spec.ts
- projects/scion/microfrontend-platform/src/lib/client/messaging/messaging.spec.ts
- projects/scion/microfrontend-platform/src/lib/host/message-broker/intent-param-validator.interceptor.ts
- projects/scion/microfrontend-platform/src/lib/host/message-broker/message-broker.ts
- projects/scion/microfrontend-platform/src/lib/host/message-broker/message-interception.spec.ts
- projects/scion/microfrontend-platform/src/lib/host/message-broker/message-interception.ts
- projects/scion/microfrontend-platform/src/lib/host/router/microfrontend-intent-navigator.interceptor.ts
- projects/scion/microfrontend-platform/src/lib/microfrontend-platform.ts
> refactor(platform/broker): move validation of intent params to an interceptor

- docs/adoc/microfrontend-platform-developer-guide/chapters/configuration/configuration.adoc
- projects/scion/microfrontend-platform/src/lib/client/client-disconnect.spec.ts
- projects/scion/microfrontend-platform/src/lib/client/messaging/broker-gateway.ts
- projects/scion/microfrontend-platform/src/lib/host/client-registry/client.constants.ts
- projects/scion/microfrontend-platform/src/lib/host/client-registry/client.ts
- projects/scion/microfrontend-platform/src/lib/host/client-registry/ɵclient.ts
- projects/scion/microfrontend-platform/src/lib/host/liveness-config.ts
- projects/scion/microfrontend-platform/src/lib/host/message-broker/message-broker.ts
- projects/scion/microfrontend-platform/src/lib/host/microfrontend-platform-config.ts
- projects/scion/microfrontend-platform/src/lib/host/public_api.ts
- projects/scion/microfrontend-platform/src/lib/microfrontend-platform.ts
- projects/scion/microfrontend-platform/src/lib/version.spec.ts
- projects/scion/microfrontend-platform/src/lib/ɵmessaging.model.ts
> fix(platform): do not unregister clients after resuming the computer from hibernation

- projects/scion/microfrontend-platform/src/lib/client/messaging/messaging.spec.ts
- projects/scion/microfrontend-platform/src/lib/client/router-outlet/outlet-router.spec.ts
- projects/scion/microfrontend-platform/src/lib/host/message-broker/intent-params.util.spec.ts
- projects/scion/microfrontend-platform/src/lib/host/message-broker/intent-params.util.ts
- projects/scion/microfrontend-platform/src/lib/host/message-broker/message-broker.ts
- projects/scion/microfrontend-platform/src/lib/microfrontend-platform.ts
> fix(platform/host): validate params of intent before passing it to interceptors

- CHANGELOG.md
- docs/site/changelog/changelog.md
- package-lock.json
- package.json
- projects/scion/microfrontend-platform/package.json
- projects/scion/microfrontend-platform/src/lib/microfrontend-platform.ts
> release: v1.0.0

- docs/adoc/microfrontend-platform-developer-guide/chapters/core-concepts/cross-application-communication/intent-based-messaging.adoc
- docs/adoc/microfrontend-platform-developer-guide/chapters/core-concepts/cross-application-communication/topic-based-messaging.adoc
- docs/adoc/microfrontend-platform-developer-guide/chapters/core-concepts/embedding-microfrontends/outlet.adoc
closes #239
Issue Number: #239
> docs(platform): fix broken links in Developer Guide documentation

- .github/workflows/workflow.yml
- CONTRIBUTING.md
- package.json
> ci(platform): create GitHub release when released to NPM

- projects/scion/microfrontend-platform/src/lib/client/router-outlet/outlet-router.spec.ts
- projects/scion/microfrontend-platform/src/lib/url.util.spec.ts
- projects/scion/microfrontend-platform/src/lib/url.util.ts
```ts
// Create blob URL
const content = '<html><body>Blob Content</body></html>';
const blobUrl = URL.createObjectURL(new Blob([content], {type: 'text/html'}));
// Navigate to the blob URL
Beans.get(OutletRouter).navigate(blobUrl);
```
> fix(platform): support navigating to blob URL

- apps/microfrontend-platform-devtools/src/app/app.component.ts
- apps/microfrontend-platform-devtools/src/app/app.config.ts
- apps/microfrontend-platform-devtools/src/app/microfrontend-platform-client/microfrontend-platform-client.provider.ts
- apps/microfrontend-platform-devtools/src/app/theme/theme-switcher.service.ts
- [r] Refactoring (changes that neither fixes a bug nor adds a feature)
> refactor(devtools): consolidate theme activation

- .github/workflows/manual-workflow.deploy-testing-app.yml
> ci(testapp): add workflow for manual deployment of testing app

- CHANGELOG.md
- CHANGELOG_LATEST.md
- docs/site/changelog/changelog.md
Previous URL: https://scion-microfrontend-platform-devtools.vercel.app
New URL: https://microfrontend-platform-devtools.scion.vercel.app,
> docs: inform about DevTools moved to `*.scion.vercel.app` subdomain

- .github/workflows/workflow.yml
- projects/scion/microfrontend-platform.e2e/playwright.config.ts
> ci: upload Playwright video on failure
